# pdf_builder.py
# ──────────────────────────────────────────────────────────────────────────────
# Converts a hybrid IMRaD markdown research report into a styled PDF with
# branding, cover page, academic section headers, and numbered references.
#
# Uses fpdf2 — a pure-Python library with zero system dependencies.
# ──────────────────────────────────────────────────────────────────────────────

import re
from datetime import datetime

from fpdf import FPDF

# ── Brand colours (RGB tuples for fpdf2) ─────────────────────────────────────
ACCENT = (27, 58, 92)
BODY   = (26, 26, 26)
MUTED  = (90, 90, 90)
LINK   = (14, 107, 168)
PRIMARY = (39, 174, 96)     # Green for PRIMARY tier
SECONDARY = (243, 156, 18)  # Amber for SECONDARY tier
TERTIARY = (192, 57, 43)    # Red for TERTIARY tier


def _sanitize(text: str) -> str:
    """Replace non-ASCII characters with ASCII equivalents for Helvetica font."""
    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2014": "-",
        "\u2013": "-",
        "\u2026": "...",
        "\u2022": "-",
        "\u00a0": " ",
        "\u00e9": "e",
        "\u00e0": "a",
        "\u00e8": "e",
        "\u00f1": "n",
        "\u2010": "-",
        "\u2011": "-",
        "\u202f": " ",
        "\ufeff": "",
    }
    for uni, asc in replacements.items():
        text = text.replace(uni, asc)
    return text.encode("ascii", "ignore").decode("ascii")


class ReportPDF(FPDF):
    """Styled PDF template for academic research reports."""

    def __init__(self, topic: str):
        super().__init__("P", "mm", "A4")
        self.topic = topic
        self.set_margins(15, 15, 15)
        self.set_auto_page_break(auto=True, margin=20)
        self._in_references = False

    # ── Page header ────────────────────────────────────────────────────────
    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*MUTED)
        self.cell(140, 8, f"Research Report | {self.topic}")
        self.cell(40, 8, f"Page {self.page_no()}", align="R")
        self.ln(1)
        self.set_draw_color(*ACCENT)
        self.set_line_width(0.2)
        self.line(15, self.get_y(), 195, self.get_y())
        self.ln(4)
        self.set_text_color(*BODY)

    # ── Page footer ────────────────────────────────────────────────────────
    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*MUTED)
        self.cell(0, 8, "Generated by Academic Research Agent", align="C")

    # ── Cover page ─────────────────────────────────────────────────────────
    def cover_page(self):
        self.add_page()
        self.ln(50)

        # Title
        self.set_font("Helvetica", "B", 28)
        self.set_text_color(*ACCENT)
        self.cell(0, 14, "Research Report", align="C", new_x="LMARGIN", new_y="NEXT")

        self.ln(6)

        # Topic
        self.set_font("Helvetica", "", 18)
        self.set_text_color(*BODY)
        self.multi_cell(0, 10, self.topic, align="C")

        self.ln(8)

        # Date
        self.set_font("Helvetica", "I", 11)
        self.set_text_color(*MUTED)
        self.cell(0, 8, datetime.now().strftime("%B %d, %Y"), align="C", new_x="LMARGIN", new_y="NEXT")

        self.ln(8)

        # Divider line
        self.set_draw_color(*ACCENT)
        self.set_line_width(0.5)
        cur_y = self.get_y()
        self.line(65, cur_y, 145, cur_y)

        self.ln(12)

        # Footer text
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*MUTED)
        self.cell(0, 6, "Academic Research Agent  |  Powered by Groq LLM", align="C")

    # ── Body rendering ─────────────────────────────────────────────────────
    def add_body(self, markdown: str):
        """Parse hybrid IMRaD markdown and render into the PDF body."""
        self.add_page()
        lines = markdown.split("\n")

        for line in lines:
            raw = line.rstrip()

            # Blank lines
            if not raw.strip():
                self.ln(2)
                continue

            # H1 — # Heading
            if raw.startswith("# ") and not raw.startswith("## "):
                self._in_references = "reference" in raw.lower()
                self._section_heading(raw[2:].strip(), size=16)

            # H2 — ## Heading (section headers)
            elif raw.startswith("## "):
                heading = raw[3:].strip()
                self._in_references = "reference" in heading.lower()
                self._section_heading(heading, size=13)

            # Reference entry — [1] [TIER] Title - URL
            elif self._in_references and re.match(r"^\s*\[\d+\]", raw):
                self._render_reference(raw.strip())

            # Bullet — - item or * item
            elif re.match(r"^\s*[-*]\s", raw):
                text = re.sub(r"^\s*[-*]\s", "", raw)
                self.set_font("Helvetica", "", 10)
                self.set_text_color(*BODY)
                self.cell(6, 6, "-")
                self.set_x(22)
                self.multi_cell(165, 5, text)

            # Numbered list — 1. item
            elif re.match(r"^\s*\d+\.\s", raw):
                self.set_font("Helvetica", "", 10)
                self.set_text_color(*BODY)
                self.multi_cell(170, 5, raw.strip())

            # Bold line — **text**
            elif "**" in raw:
                self.set_font("Helvetica", "B", 10)
                self.set_text_color(*BODY)
                self.multi_cell(170, 5, raw.replace("**", "").strip())

            # Citation markers — [1], [2], [3] inline
            elif re.match(r"^\s*\[\d+\]", raw):
                self.set_font("Helvetica", "", 10)
                self.set_text_color(*BODY)
                self.multi_cell(170, 5, raw.strip())

            # Normal paragraph text
            else:
                self.set_font("Helvetica", "", 10)
                self.set_text_color(*BODY)
                self.multi_cell(170, 5, raw.strip())

    def _section_heading(self, text: str, size: int):
        """Render a styled section heading with underline."""
        self.ln(3)
        self.set_font("Helvetica", "B", size)
        self.set_text_color(*ACCENT)
        self.multi_cell(170, size * 0.6, text)
        # Underline
        y = self.get_y()
        self.set_draw_color(*ACCENT)
        self.set_line_width(0.3)
        underline_len = min(170, len(text) * size * 0.35)
        self.line(15, y, 15 + underline_len, y)
        self.set_y(y + 2)
        self.set_text_color(*BODY)

    def _render_reference(self, text: str):
        """Render a reference entry with tier-colored label."""
        self.set_font("Helvetica", "", 9)

        # Extract tier label if present
        tier_match = re.search(r"\[(PRIMARY|SECONDARY|TERTIARY)\]", text)
        if tier_match:
            tier = tier_match.group(1)
            if tier == "PRIMARY":
                self.set_text_color(*PRIMARY)
            elif tier == "SECONDARY":
                self.set_text_color(*SECONDARY)
            else:
                self.set_text_color(*TERTIARY)

            # Print the numbered entry + tier
            clean = re.sub(r"\s*\[(PRIMARY|SECONDARY|TERTIARY)\]", "", text)
            self.multi_cell(170, 4.5, clean.strip())
            self.set_text_color(*BODY)
        else:
            self.set_text_color(*LINK)
            self.multi_cell(170, 4.5, text.strip())
            self.set_text_color(*BODY)


def generate_pdf(markdown_report: str, topic: str) -> bytes:
    """
    Generate a styled PDF from a hybrid IMRaD markdown report.

    Args:
        markdown_report: The full markdown text from the Writer agent.
        topic: The research topic (used on the cover page).

    Returns:
        PDF file contents as bytes.
    """
    pdf = ReportPDF(_sanitize(topic))
    pdf.set_compression(True)
    pdf.cover_page()
    pdf.add_body(_sanitize(markdown_report))
    return bytes(pdf.output())
